# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: csv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='csv.proto',
  package='csv',
  syntax='proto3',
  serialized_pb=_b('\n\tcsv.proto\x12\x03\x63sv\"C\n\x07\x43SVFile\x12\x1e\n\x06header\x18\x01 \x03(\x0b\x32\x0e.csv.CSVHeader\x12\x18\n\x03row\x18\x02 \x03(\x0b\x32\x0b.csv.CSVRow\" \n\tCSVHeader\x12\x13\n\x0b\x63olumn_name\x18\x01 \x03(\t\"\x1e\n\x06\x43SVRow\x12\x14\n\x0c\x63olumn_value\x18\x01 \x03(\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CSVFILE = _descriptor.Descriptor(
  name='CSVFile',
  full_name='csv.CSVFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='csv.CSVFile.header', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='row', full_name='csv.CSVFile.row', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=85,
)


_CSVHEADER = _descriptor.Descriptor(
  name='CSVHeader',
  full_name='csv.CSVHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column_name', full_name='csv.CSVHeader.column_name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=119,
)


_CSVROW = _descriptor.Descriptor(
  name='CSVRow',
  full_name='csv.CSVRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column_value', full_name='csv.CSVRow.column_value', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=151,
)

_CSVFILE.fields_by_name['header'].message_type = _CSVHEADER
_CSVFILE.fields_by_name['row'].message_type = _CSVROW
DESCRIPTOR.message_types_by_name['CSVFile'] = _CSVFILE
DESCRIPTOR.message_types_by_name['CSVHeader'] = _CSVHEADER
DESCRIPTOR.message_types_by_name['CSVRow'] = _CSVROW

CSVFile = _reflection.GeneratedProtocolMessageType('CSVFile', (_message.Message,), dict(
  DESCRIPTOR = _CSVFILE,
  __module__ = 'csv_pb2'
  # @@protoc_insertion_point(class_scope:csv.CSVFile)
  ))
_sym_db.RegisterMessage(CSVFile)

CSVHeader = _reflection.GeneratedProtocolMessageType('CSVHeader', (_message.Message,), dict(
  DESCRIPTOR = _CSVHEADER,
  __module__ = 'csv_pb2'
  # @@protoc_insertion_point(class_scope:csv.CSVHeader)
  ))
_sym_db.RegisterMessage(CSVHeader)

CSVRow = _reflection.GeneratedProtocolMessageType('CSVRow', (_message.Message,), dict(
  DESCRIPTOR = _CSVROW,
  __module__ = 'csv_pb2'
  # @@protoc_insertion_point(class_scope:csv.CSVRow)
  ))
_sym_db.RegisterMessage(CSVRow)


# @@protoc_insertion_point(module_scope)
